### ISSUE TITLE
🩹 Fix: Re-align Rate Limiter code block

### ISSUE THREAD

**Issue by grivera64** [gofiber/website#110]
On https://gofiber.io, the rate limiter section has a misaligned code block for `limiter.Config{}`:

<img width="543" alt="image" src="https://github.com/user-attachments/assets/fcc5d633-3510-4d8e-bf06-b13f9d7a0851">

This can be fixed by updating [components/blocks/RateLimiter.tsx](https://github.com/gofiber/website/blob/master/components/blocks/RateLimiter.tsx#L20) to add extra spaces (2 spaces most likely will do).

If it is okay, I can take on this issue.

**Comment by gaby** [comment]
@grivera64 This is managed in the main repo. It gets sync here

**Comment by grivera64** [comment]
> @grivera64 ~This is managed in the main repo. It gets sync here~
> 
> I think that one is here 😂

Haha, no worries. I can make the PR here to update the home page with the fix.
